/*
 * generated by Xtext 2.27.0
 */
package htmlDSL.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import htmlDSL.XtmlRuntimeModule;
import htmlDSL.XtmlStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class XtmlIdeSetup extends XtmlStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new XtmlRuntimeModule(), new XtmlIdeModule()));
	}
	
}
