/*
 * generated by Xtext 2.27.0
 */
package htmlDSL.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class XtmlUiModule extends AbstractXtmlUiModule {

	public XtmlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
		
	}
}
